name: batur
description: "Bandung Tourism App Project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.2
  google_fonts:
  equatable:
  flutter_bloc:
  flutter_native_splash:
  flutter_svg: 
  tuple: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  image: assets/splashscreen/logo.png
  background_image: assets/splashscreen/bgsplashscreen.png
  background_image_dark: assets/splashscreen/bgsplashscreen_dark.png
  image_dark: assets/splashscreen/logo_dark.png
  android_12:
    image: assets/splashscreen/logo.png
    image_dark: assets/splashscreen/logo_dark.png

  web: false

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo/
    - assets/logo/logo.png
    - assets/logo/logo_dark.png

    - assets/icons/
    - assets/icons/eye_outline.svg
    - assets/icons/eye_slash_outline.svg
    - assets/icons/lock_outline.svg
    - assets/icons/user_outline.svg
    - assets/icons/google.svg
    - assets/icons/facebook.svg

    - assets/images/onboarding.png
  