// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2aAoGalG_PNy9Vg_FjamuiU6-unVpanI',
    appId: '1:791822441851:web:c63c2b118ab8f4098c31de',
    messagingSenderId: '791822441851',
    projectId: 'batur-958b8',
    authDomain: 'batur-958b8.firebaseapp.com',
    storageBucket: 'batur-958b8.appspot.com',
    measurementId: 'G-QH3NV2DFJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjuQGPNfqSmY44u0KDSvGFp4hwf9pMC80',
    appId: '1:791822441851:android:87dedcc6aad19b158c31de',
    messagingSenderId: '791822441851',
    projectId: 'batur-958b8',
    storageBucket: 'batur-958b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRkOiZfMRye9V5FrrkoPB-6maDjf7B_X8',
    appId: '1:791822441851:ios:b29c9f30307180ba8c31de',
    messagingSenderId: '791822441851',
    projectId: 'batur-958b8',
    storageBucket: 'batur-958b8.appspot.com',
    iosBundleId: 'com.example.batur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRkOiZfMRye9V5FrrkoPB-6maDjf7B_X8',
    appId: '1:791822441851:ios:66bf5a96a9410f608c31de',
    messagingSenderId: '791822441851',
    projectId: 'batur-958b8',
    storageBucket: 'batur-958b8.appspot.com',
    iosBundleId: 'com.example.batur.RunnerTests',
  );
}
